import type { RawQuestionRow } from "./question-types.ts";

export const rows: RawQuestionRow[] = [
  ["think they are funnier than they actually are?", "humour", "humour"],
  ["be the hardest person here to live with?", "responsibility", "habits"],
  ["get rejected and pretend they never cared?", "romance", "romance"],
  ["say 'I knew that' immediately after someone explains it?", "intelligence", "ego"],
  ["give advice they absolutely do not follow themselves?", "responsibility", "advice"],
  ["take the longest to admit they were wrong?", "responsibility", "ego"],
  ["stalk the menu before going to the restaurant?", null, "food"],
  ["act the busiest while doing the least?", "responsibility", "work"],
  ["reply 'haha' when they did not laugh at all?", "social", "phone"],
  ["have the most unrealistic confidence in their navigation skills?", "responsibility", "travel"],
  ["borrow something and forget it is not theirs?", "responsibility", "habits"],
  ["lose an argument and change the topic?", "social", "argument"],
  ["say they are almost ready with zero evidence of being ready?", "responsibility", "late"],
  ["become dramatic after one minor inconvenience?", "chaos", "drama"],
  ["pretend not to care about winning and then care the most?", "main_character", "games"],
  ["check who viewed something five times?", "social", "phone"],
  ["complain about being tired after doing the least walking?", "responsibility", "habits"],
  ["say 'one episode' and disappear for six hours?", null, "entertainment"],
  ["be most likely to leave the group chat and return five minutes later?", "chaos", "drama"],
  ["judge everyone's order and then ask for a bite?", null, "food"],
  ["have the strongest opinions about things they barely understand?", "intelligence", "ego"],
  ["say 'I don't need directions' right before getting lost?", "responsibility", "travel"],
  ["make a tiny problem sound like a documentary?", "chaos", "drama"],
  ["take a compliment and somehow turn it into a speech?", "main_character", "ego"],
  ["be the reason plans start thirty minutes late?", "responsibility", "late"],
  ["forget what they said and confidently deny saying it?", "responsibility", "memory"],
  ["claim they are low-maintenance while proving otherwise?", "main_character", "habits"],
  ["say they hate gossip and then know every detail?", "social", "drama"],
  ["pick a fight with autocorrect instead of fixing the typo?", "chaos", "phone"],
  ["have the most screenshots they will never look at again?", "chaos", "phone"],
  ["say 'I'm fine' in the least convincing way possible?", "social", "drama"],
  ["overthink a two-word reply for twenty minutes?", "social", "phone"],
  ["promise to keep something short and then write an essay?", "social", "story"],
  ["be the first to blame the Wi-Fi?", "chaos", "tech"],
  ["forget their own suggestion and complain about it later?", "responsibility", "memory"],
  ["act like the main character in an ordinary grocery store?", "main_character", "main"],
  ["use 'busy' as a personality trait for the week?", "responsibility", "work"],
  ["take a harmless joke personally for exactly three minutes?", "humour", "humour"],
  ["start a sentence with 'not to be dramatic' and be extremely dramatic?", "chaos", "drama"],
  ["say 'I can explain' with the least helpful explanation?", "chaos", "story"],
  ["be most likely to read the terms and still click the wrong button?", "intelligence", "tech"],
  ["get caught pretending they remembered someone's name?", "social", "social"],
  ["turn being five minutes late into a full origin story?", "humour", "late"],
  ["have the most confidence with the least battery percentage?", "chaos", "phone"],
  ["say 'I was just about to do that' after being reminded?", "responsibility", "habits"]
];
