import type { RawQuestionRow } from "./question-types.ts";

export const rows: RawQuestionRow[] = [
  ["become a millionaire first?", "success", "success"],
  ["build a company people actually know?", "success", "business"],
  ["move to another country for the right opportunity?", "adventure", "career"],
  ["learn a difficult skill just because they decided to?", "intelligence", "learning"],
  ["turn a side project into a real career?", "success", "career"],
  ["become the boss without acting like one?", "success", "leadership"],
  ["make the smartest long-term decision under pressure?", "intelligence", "decision"],
  ["actually finish the ambitious plan everyone else forgot about?", "success", "discipline"],
  ["be trusted to lead the group through a difficult decision?", "trust", "leadership"],
  ["invent something unexpectedly useful?", "intelligence", "innovation"],
  ["be the first to own their dream home?", "success", "success"],
  ["turn one good connection into a huge opportunity?", "social", "career"],
  ["handle money the most responsibly over ten years?", "responsibility", "money"],
  ["switch careers successfully if they got bored?", "courage", "career"],
  ["become known for being excellent at one thing?", "success", "career"],
  ["learn a new language the fastest?", "intelligence", "learning"],
  ["stay disciplined after the motivation disappears?", "success", "discipline"],
  ["make the boldest career move and have it pay off?", "courage", "career"],
  ["be the best negotiator in a serious situation?", "social", "career"],
  ["spot a business opportunity before everyone else?", "intelligence", "business"],
  ["keep going longest on a difficult goal?", "courage", "discipline"],
  ["be invited to speak about what they do one day?", "success", "fame"],
  ["make the best first impression in an important room?", "social", "career"],
  ["build the strongest professional network?", "social", "career"],
  ["take a huge calculated risk at exactly the right time?", "courage", "decision"],
  ["become the person everyone asks for expert advice?", "intelligence", "career"],
  ["retire early because they planned absurdly well?", "responsibility", "money"],
  ["turn a failure into the best comeback story?", "courage", "success"],
  ["lead a team people genuinely enjoy working with?", "social", "leadership"],
  ["be most likely to quietly become very successful?", "success", "success"],
  ["make a difficult technical problem look easy?", "intelligence", "learning"],
  ["start over from zero and still figure it out?", "courage", "success"],
  ["be the most convincing in a high-stakes pitch?", "social", "business"],
  ["choose the best person to partner with on a big idea?", "trust", "business"],
  ["actually stick to a five-year plan?", "responsibility", "discipline"]
];
