import type { RawQuestionRow } from "./question-types.ts";

export const rows: RawQuestionRow[] = [
  ["accidentally get arrested?", "chaos", "law"],
  ["lose their passport during a trip?", "responsibility", "travel"],
  ["start drama and then act shocked that there is drama?", "chaos", "drama"],
  ["book a flight for the wrong date?", "responsibility", "travel"],
  ["end up on the news for something ridiculous?", "main_character", "fame"],
  ["talk their way into a VIP area they do not belong in?", "social", "party"],
  ["survive a zombie apocalypse for the weirdest reason?", "courage", "survival"],
  ["accidentally become the leader of a strange club?", "main_character", "social"],
  ["miss their own train while standing on the platform?", "chaos", "travel"],
  ["turn a small misunderstanding into a three-season storyline?", "chaos", "drama"],
  ["wake up in a different city with the funniest explanation?", "adventure", "travel"],
  ["get banned from a place for a completely harmless but ridiculous reason?", "chaos", "law"],
  ["buy something wildly unnecessary at 2 AM?", "chaos", "shopping"],
  ["start a business on impulse and somehow make money?", "success", "business"],
  ["go viral without trying?", "main_character", "fame"],
  ["accidentally send a private message to the group chat?", "chaos", "phone"],
  ["be chased by an animal on vacation?", "adventure", "travel"],
  ["say 'trust me' right before everything goes wrong?", "chaos", "decision"],
  ["turn a calm trip into a full adventure movie?", "adventure", "travel"],
  ["make friends with the person they were arguing with five minutes ago?", "social", "argument"],
  ["forget they have something important tomorrow and stay out anyway?", "responsibility", "plans"],
  ["accidentally become responsible for an entire group of strangers?", "responsibility", "social"],
  ["find a loophole nobody else noticed?", "intelligence", "scheme"],
  ["convince everyone to do something that sounds terrible but becomes a great story?", "main_character", "adventure"],
  ["be the reason the group needs a backup plan?", "chaos", "plans"],
  ["get lost with full GPS signal?", "responsibility", "travel"],
  ["show up to the wrong event and stay anyway?", "social", "social"],
  ["accidentally start a rumour about themselves?", "chaos", "drama"],
  ["win a ridiculous bet nobody expected them to win?", "courage", "games"],
  ["make a terrible decision with unbelievable confidence?", "chaos", "decision"],
  ["turn a minor inconvenience into a legendary group story?", "humour", "story"],
  ["be the first to say 'what if we just...' and make everyone nervous?", "chaos", "scheme"],
  ["get invited somewhere by people they met ten minutes ago?", "social", "party"],
  ["accidentally reveal a surprise too early?", "responsibility", "secret"],
  ["become a meme in the friend group?", "humour", "humour"],
  ["make the boldest choice on a menu and instantly regret it?", "courage", "food"],
  ["say yes to a random road trip with almost no questions?", "adventure", "travel"],
  ["start negotiating when the price is clearly fixed?", "social", "shopping"],
  ["break something while trying to fix it?", "chaos", "diy"],
  ["discover a hidden place by taking a wrong turn?", "adventure", "travel"],
  ["cause a security guard to remember the whole group?", "chaos", "law"],
  ["turn an ordinary birthday into a logistical crisis?", "chaos", "party"],
  ["accidentally join the wrong online meeting and stay too long?", "chaos", "tech"],
  ["get the group into an argument with another group over something pointless?", "chaos", "argument"],
  ["walk away from a disaster looking suspiciously untouched?", "courage", "survival"],
  ["invent a fake backstory on the spot and commit to it all night?", "humour", "story"],
  ["make a spontaneous purchase that becomes everyone's favorite thing?", "main_character", "shopping"],
  ["forget a suitcase somewhere and notice hours later?", "responsibility", "travel"],
  ["be trusted with the map and still lead everyone the wrong way?", "responsibility", "travel"],
  ["take a harmless prank way too professionally?", "chaos", "prank"],
  ["win over someone's parents within five minutes?", "social", "social"],
  ["end up backstage at an event by pure accident?", "adventure", "fame"],
  ["turn a dare into a full personal mission?", "courage", "dare"],
  ["be the first person questioned when something mysteriously disappears?", "chaos", "mystery"],
  ["make an emergency plan that somehow creates a second emergency?", "chaos", "plans"],
  ["accidentally expose the group's inside joke in public?", "chaos", "secret"],
  ["get everyone kicked out of a quiet place for laughing?", "humour", "humour"],
  ["talk to a celebrity without realizing who they are?", "social", "fame"],
  ["decide to learn a dangerous-looking skill from one tutorial?", "courage", "hobby"],
  ["make a simple shortcut take twice as long?", "chaos", "travel"],
  ["be the only one calm during a completely ridiculous emergency?", "courage", "survival"],
  ["accidentally start a competition nobody asked for?", "chaos", "games"],
  ["show up with exactly the weird item that suddenly saves the day?", "responsibility", "prepared"],
  ["make a stranger tell them their entire life story?", "social", "social"],
  ["become weirdly famous in a very specific online community?", "main_character", "fame"],
  ["turn a wrong number call into a ten-minute conversation?", "social", "phone"],
  ["volunteer the group for something before asking anyone?", "chaos", "plans"],
  ["mistake a serious situation for a joke at first?", "humour", "humour"],
  ["escape a bad situation using pure confidence?", "courage", "survival"],
  ["be the reason someone says 'this is why we can't have nice things'?", "chaos", "chaos"]
];
