import type { RawQuestionRow } from "./question-types.ts";

export const rows: RawQuestionRow[] = [
  ["take the longest to get ready?", "responsibility", "habits"],
  ["sleep through an apocalypse alarm?", "chaos", "sleep"],
  ["lose their phone first on a night out?", "responsibility", "forgetful"],
  ["order the exact same thing every time?", null, "food"],
  ["have 37 unread messages and feel completely fine?", "social", "phone"],
  ["say 'five minutes away' while still at home?", "responsibility", "late"],
  ["forget where they parked?", "responsibility", "forgetful"],
  ["become best friends with a random stranger in a queue?", "social", "social"],
  ["finish everyone else's fries?", null, "food"],
  ["bring snacks to a situation that absolutely does not need snacks?", "responsibility", "food"],
  ["fall asleep during a movie they chose?", "chaos", "sleep"],
  ["laugh at the worst possible moment?", "humour", "humour"],
  ["have the most chaotic camera roll?", "chaos", "phone"],
  ["know every shortcut through the city?", "intelligence", "travel"],
  ["forget someone's birthday but remember a useless fact from 2018?", "responsibility", "memory"],
  ["spend twenty minutes choosing what to watch and then watch nothing?", null, "entertainment"],
  ["turn a two-minute story into a fifteen-minute story?", "social", "story"],
  ["be the first to suggest getting food?", null, "food"],
  ["send the funniest reaction image in the group chat?", "humour", "humour"],
  ["have a playlist for an absurdly specific mood?", "main_character", "music"],
  ["re-watch the same comfort show forever?", null, "entertainment"],
  ["walk into a room and forget why they went there?", "responsibility", "forgetful"],
  ["make a simple errand somehow take three hours?", "chaos", "errand"],
  ["show up with the most overpacked bag?", "responsibility", "travel"],
  ["have the best food recommendations?", "social", "food"],
  ["survive a week using only leftovers?", "responsibility", "food"],
  ["start dancing when nobody else is dancing?", "social", "party"],
  ["accidentally wear the exact same outfit twice in one week?", null, "style"],
  ["say they are not hungry and then eat half your food?", null, "food"],
  ["remember everyone's weirdly specific order?", "intelligence", "memory"],
  ["have the most tabs open right now?", "chaos", "tech"],
  ["turn up ten minutes early everywhere?", "responsibility", "time"],
  ["reply instantly at 3 AM?", "social", "phone"],
  ["be impossible to wake up before noon?", "chaos", "sleep"],
  ["carry the most random useful item in their bag?", "responsibility", "prepared"],
  ["win a game they claimed they had never played before?", "intelligence", "games"],
  ["take the best candid photos of everyone?", "social", "photos"],
  ["become obsessed with a hobby for exactly two weeks?", "main_character", "hobby"],
  ["have the cleanest home screen on their phone?", "responsibility", "phone"],
  ["be most likely to miss a call while holding their phone?", "chaos", "phone"],
  ["know the lyrics but absolutely not the song title?", "humour", "music"],
  ["create a spreadsheet for something that does not need a spreadsheet?", "responsibility", "organized"],
  ["be the designated photographer without being asked?", "social", "photos"],
  ["make the best late-night snack?", null, "food"],
  ["have the strangest sleep schedule?", "chaos", "sleep"],
  ["spend the longest choosing a profile picture?", "social", "photos"],
  ["be weirdly good at guessing passwords that are not actually passwords?", "intelligence", "games"],
  ["turn a quiet car ride into a full concert?", "humour", "music"],
  ["own something for years and never remove the protective sticker?", "responsibility", "habits"],
  ["know exactly where the best seat in any room is?", "intelligence", "comfort"],
  ["finish a whole series in one weekend?", null, "entertainment"],
  ["have the most organized notes and the messiest desk?", "responsibility", "organized"],
  ["say 'I'm on my way' before actually leaving?", "responsibility", "late"],
  ["win an argument using one perfectly timed sentence?", "intelligence", "argument"],
  ["be the first person everyone asks for a charger?", "responsibility", "prepared"]
];
