import type { RawQuestionRow } from "./question-types.ts";

export const rows: RawQuestionRow[] = [
  ["give the best advice when it actually matters?", "trust", "advice"],
  ["be the first person you call during an emergency?", "trust", "emergency"],
  ["travel across the city just to help a friend?", "loyalty", "loyalty"],
  ["remember the little things people say?", "loyalty", "memory"],
  ["make a new person feel included immediately?", "social", "kindness"],
  ["keep the biggest secret without slipping once?", "trust", "secret"],
  ["notice when someone is quiet before anyone else does?", "social", "kindness"],
  ["make the best person to have on your side in a crisis?", "trust", "emergency"],
  ["actually show up when they say 'call me if you need anything'?", "loyalty", "loyalty"],
  ["make a bad day better without trying too hard?", "humour", "kindness"],
  ["be the most patient teacher in the group?", "intelligence", "advice"],
  ["give the most thoughtful gift?", "loyalty", "gift"],
  ["defend a friend even when they are not in the room?", "loyalty", "loyalty"],
  ["be trusted to handle something genuinely important?", "responsibility", "trust"],
  ["make everyone feel calmer when things go wrong?", "courage", "emergency"],
  ["remember a birthday without a reminder?", "loyalty", "memory"],
  ["be the best travel companion on a long trip?", "adventure", "travel"],
  ["share their last snack without making it weird?", "loyalty", "food"],
  ["be the first to congratulate someone properly?", "social", "kindness"],
  ["make friends across completely different groups?", "social", "social"],
  ["be trusted with someone's pet for a week?", "responsibility", "trust"],
  ["help someone move without suddenly becoming unavailable?", "loyalty", "loyalty"],
  ["give honest feedback without making it hurt?", "trust", "advice"],
  ["be the best person to sit next to on a terrible day?", "trust", "kindness"],
  ["stay calm enough to solve the problem first?", "courage", "emergency"],
  ["remember exactly how everyone takes their coffee?", "loyalty", "memory"],
  ["be most likely to check that everyone got home safely?", "responsibility", "safety"],
  ["organize the group when everyone else is confused?", "responsibility", "plans"],
  ["be genuinely happy when a friend succeeds?", "loyalty", "success"],
  ["make someone laugh when they really need it?", "humour", "kindness"],
  ["keep a promise even when it becomes inconvenient?", "loyalty", "trust"],
  ["be the person you'd trust to speak for you if you could not?", "trust", "trust"],
  ["make an awkward situation feel normal?", "social", "social"],
  ["be the most dependable on a group project?", "responsibility", "work"],
  ["notice the person who has not been included yet?", "social", "kindness"],
  ["give credit instead of taking it?", "responsibility", "work"],
  ["keep a cool head in an actual emergency?", "courage", "emergency"],
  ["be the best person to ask for a reality check?", "trust", "advice"],
  ["make the best effort to stay in touch over the years?", "loyalty", "friendship"],
  ["be trusted to plan a surprise without ruining it?", "responsibility", "secret"],
  ["help fix a mistake without making the person feel worse?", "trust", "kindness"],
  ["be the best at cheering someone on before a big moment?", "loyalty", "success"],
  ["become the unofficial responsible adult of the group?", "responsibility", "responsibility"],
  ["make everyone feel welcome at their place?", "social", "kindness"],
  ["give up their seat without making a performance of it?", "loyalty", "kindness"],
  ["keep everyone together on a chaotic trip?", "responsibility", "travel"],
  ["be trusted with the group budget?", "responsibility", "money"],
  ["be the easiest person to talk to about something serious?", "trust", "trust"],
  ["support a friend through a long difficult goal?", "loyalty", "success"],
  ["make a stranger feel safe asking for help?", "social", "kindness"]
];
